//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyamProject.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageIngredient
    {
        public int Ingredient_stage_id { get; set; }
        public Nullable<int> ingredient_id { get; set; }
        public Nullable<decimal> ingredient_qnt { get; set; }
        public Nullable<int> stage_id { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual StageOfCooking StageOfCooking { get; set; }
    }
}
